services:
  app:
    image: ${IMAGE_URI}
    container_name: helthix
    ports:
      - '3000:3000'
    restart: always

    env_file:
      - .env

    environment:
      NODE_ENV: production
      PORT: '3000'

    networks:
      - helthix-network

networks:
  helthix-network:
    driver: bridge
