services:
  app:
    image: ${IMAGE_URI}
    container_name: shm
    ports:
      - '3000:3000'
    restart: always

    env_file:
      - .env

    environment:
      NODE_ENV: production
      PORT: '3000'

    networks:
      - shm-network

networks:
  shm-network:
    driver: bridge
